### ISSUE TITLE
Add .idea folder to .gitignore

### ISSUE THREAD

**Issue by veyndan** [davidalbers/whitenoise#11]
Folder is specific to the individuals Android Studio set up so committing of folder is unnecessary.

**Comment by davidalbers** [comment]
I updated the .gitignore using [this](https://www.gitignore.io/api/android%2Cintellij%2Cmacos%2Cwindows). It doesn't ignore the whole .idea folder because some people on StackOverflow said that was a bad idea. Thanks though, it needed updated.
