### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by Cj-Malone** [davidalbers/whitenoise#12]
I dropped appcompat, appindexing and butterknife from this and TimerPickerLibrary, the apk was 6.12MB from 12.37MB.

Butterknife is overkill for a one activity project. I still don't understand what AppIndexing is doing. And while removing AppCompat I kept the minSdk at 19 so I don't think that's vital either.

Let me know if you're OK with any of these being dropped and I'll open some pull requests.

**Comment by davidalbers** [comment]
- Butterknife, I'd like to keep. I just use it by default in my projects now and it makes the code nicer to read. Although, how big is it? I guess if it's really big we could drop it.
- TimerPickerLIbrary, I made this one haha. But what did you use instead for setting a timer? If you found a better library or whatever, it's fine. I'd be interested to know though, maybe I could optimise TimerPicker.
- AppIndexing, yeah drop it.
- AppCompat, if it still works without it, that's fine.

**Comment by Cj-Malone** [comment]
I wasn't recommending dropping TimerPickerLibrary, just saying that I dropped appcompat from it for the small build however that did require a min version bump so I'm not going to do a PR.

I've dropped AppIndexing [here](https://github.com/Cj-Malone/whitenoise/commits/master), however my builds are now a lot larger than the Google Play APK so I'll look again in tomorrow.
