### ISSUE TITLE
Proposition to use Checkstyle and Travis

### ISSUE THREAD

**Issue by veyndan** [davidalbers/whitenoise#15]
The formatting of the code is very inconsistent. My proposition is that we set up Travis to watch the project which in turn we can run Checkstyle for each PR. I can set up the `.travis.yml` file and the necessary Checkstyle configurations but as I'm not an administrator of this project, I can't enable Travis on the repository which is done through Travis's site.

I don't know how much you know about Travis but here's the quick start guide: [https://docs.travis-ci.com/user/getting-started/](https://docs.travis-ci.com/user/getting-started/).

**Comment by davidalbers** [comment]
Good idea! I set up Travis, but don't have any experience with Checkstyle. I've used Sonarlint locally in this project, but Checkstyle looks good also.

**Comment by veyndan** [comment]
Cool, one of the more popular Checkstyle configurations is based on [Google's Java Style Guide](https://google.github.io/styleguide/javaguide.html). I'd propose using that with the minor change that indentations should be 4 spaces instead of 2.

**Comment by davidalbers** [comment]
Google's style guide is fine with me. And, yeah, 4 spaces instead of 2.
